name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2
        with:
           php-version: 7.4
      - name: install composer dependencies
        run: composer update
      - name: generate key
        run: php artisan key:generate
      - name: migrate database
        run: php artisan migrate --seed
      - name: run tests
        run: ./vendor/bin/phpunit

      - uses: atymic/deployer-php-action@0.3.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          ssh-disable-host-key-checking: true
